CREATE TABLE IF NOT EXISTS "doctors" (
NPI varchar Primary Key,
"personal"."last_name" varchar,
"personal"."first_name" varchar,
"personal"."middle_name" varchar,
"personal"."suffix" varchar,
"personal"."gender" varchar,
"medical"."credentials" varchar,
"medical"."med_school" varchar,
"medical"."grad_year" varchar,
"medical"."primary_spec" varchar,
"medical"."secondary_spec" varchar,
"medical"."tertiary_spec" varchar,
"medical"."quaternary_spec" varchar,
"medical"."quinary_spec" varchar,
"medical"."all_spec" varchar,
"personal"."street" varchar,
"personal"."city" varchar,
"personal"."state" varchar,
"personal"."zip" varchar);
