CREATE TABLE IF NOT EXISTS STOCKS (
SYMBOL VARCHAR NOT NULL,
OPEN DECIMAL(6,2),
HIGH DECIMAL(6,2),
LOW DECIMAL(6,2),
CLOSE DECIMAL(6,2),
VOLUME INTEGER,
ADJ_CLOSE DECIMAL(6,2),
RECORD_DATE DATE NOT NULL,
CONSTRAINT PK PRIMARY KEY (SYMBOL, RECORD_DATE));
