#-*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

VAGRANT_DEFAULT_PROVIDER = "vmware"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
      config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

  config.vm.provision "shell", path: "setup.sh"

  config.vm.define "master" do |master|
    master.vm.box = "bento/centos-6.7"
    master.vm.hostname = "cluster.master"
    master.vm.network "private_network", ip: "192.168.110.10"
    master.vm.network "forwarded_port", guest: 8983, host: 8983
    master.vm.network "forwarded_port", guest: 8764, host: 8764
    master.vm.network "forwarded_port", guest: 8765, host: 8765
    master.vm.network "forwarded_port", guest: 8984, host: 8984
    master.hostmanager.aliases = %w(cluster)
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "6144"]
  end

end
